[project]
name = "multimodal-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.6",
    "llama-index-embeddings-huggingface>=0.6.0",
    "qdrant-client>=1.15.1",
]
